name: noveru
description: "find my novel."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod:
  cupertino_icons: ^1.0.8
  flutter_card_swiper: ^7.0.2
  loading_animation_widget: ^1.3.0
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  csv: ^6.0.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  external_app_launcher: ^4.0.1
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/noveru.csv
    - assets/images/

  fonts:
    - family: Noto_Serif_JP
      fonts:
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-VariableFont_wght.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon_512.png"